name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  test-and-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --cov=src tests/

      - name: Run Pylint
        run: |
          pip install pylint
          pylint src/**/*.py